from weather.weatherdata import Weather

w = Weather("Toronto", "Canada")
print("City: " + w.get_city())
print("Country code:" + w.get_code())
print("Description: " + w.get_description())
print("Humidity: " + str(w.get_humidity()))
print("Status: " + w.get_status())
print("Temperature C:" + str(w.get_temperature("c")))
print("Temperature F:" + str(w.get_temperature("f")))
print("Temperature K:" + str(w.get_temperature("k")))
print("Temperature Max C:" + str(w.get_temperature("c", 1)))
print("Temperature Min C:" + str(w.get_temperature("c", -1)))
print("Wind speed: " + str(w.get_wind_speed()))
print()
print()
w.set_new_location("New York", "United States")
print("City: " + w.get_city())
print("Country code:" + w.get_code())
print("Description: " + w.get_description())
print("Humidity: " + str(w.get_humidity()))
print("Status: " + w.get_status())
print("Temperature C:" + str(w.get_temperature("c")))
print("Temperature F:" + str(w.get_temperature("f")))
print("Temperature K:" + str(w.get_temperature("k")))
print("Temperature Max C:" + str(w.get_temperature("c", 1)))
print("Temperature Min C:" + str(w.get_temperature("c", -1)))
print("Wind speed: " + str(w.get_wind_speed()))
print()
print()
