# CMake generated Testfile for 
# Source directory: /Users/orlandoortega/Desktop/NotificationBot/libraries/cpr/test
# Build directory: /Users/orlandoortega/Desktop/NotificationBot/libraries/cpr/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(cpr_get_tests "/Users/orlandoortega/Desktop/NotificationBot/bin/get_tests")
set_tests_properties(cpr_get_tests PROPERTIES  _BACKTRACE_TRIPLES "/Users/orlandoortega/Desktop/NotificationBot/libraries/cpr/test/CMakeLists.txt;16;add_test;/Users/orlandoortega/Desktop/NotificationBot/libraries/cpr/test/CMakeLists.txt;37;add_cpr_test;/Users/orlandoortega/Desktop/NotificationBot/libraries/cpr/test/CMakeLists.txt;0;")
add_test(cpr_post_tests "/Users/orlandoortega/Desktop/NotificationBot/bin/post_tests")
set_tests_properties(cpr_post_tests PROPERTIES  _BACKTRACE_TRIPLES "/Users/orlandoortega/Desktop/NotificationBot/libraries/cpr/test/CMakeLists.txt;16;add_test;/Users/orlandoortega/Desktop/NotificationBot/libraries/cpr/test/CMakeLists.txt;38;add_cpr_test;/Users/orlandoortega/Desktop/NotificationBot/libraries/cpr/test/CMakeLists.txt;0;")
add_test(cpr_session_tests "/Users/orlandoortega/Desktop/NotificationBot/bin/session_tests")
set_tests_properties(cpr_session_tests PROPERTIES  _BACKTRACE_TRIPLES "/Users/orlandoortega/Desktop/NotificationBot/libraries/cpr/test/CMakeLists.txt;16;add_test;/Users/orlandoortega/Desktop/NotificationBot/libraries/cpr/test/CMakeLists.txt;39;add_cpr_test;/Users/orlandoortega/Desktop/NotificationBot/libraries/cpr/test/CMakeLists.txt;0;")
add_test(cpr_async_tests "/Users/orlandoortega/Desktop/NotificationBot/bin/async_tests")
set_tests_properties(cpr_async_tests PROPERTIES  _BACKTRACE_TRIPLES "/Users/orlandoortega/Desktop/NotificationBot/libraries/cpr/test/CMakeLists.txt;16;add_test;/Users/orlandoortega/Desktop/NotificationBot/libraries/cpr/test/CMakeLists.txt;40;add_cpr_test;/Users/orlandoortega/Desktop/NotificationBot/libraries/cpr/test/CMakeLists.txt;0;")
add_test(cpr_proxy_tests "/Users/orlandoortega/Desktop/NotificationBot/bin/proxy_tests")
set_tests_properties(cpr_proxy_tests PROPERTIES  _BACKTRACE_TRIPLES "/Users/orlandoortega/Desktop/NotificationBot/libraries/cpr/test/CMakeLists.txt;16;add_test;/Users/orlandoortega/Desktop/NotificationBot/libraries/cpr/test/CMakeLists.txt;41;add_cpr_test;/Users/orlandoortega/Desktop/NotificationBot/libraries/cpr/test/CMakeLists.txt;0;")
add_test(cpr_head_tests "/Users/orlandoortega/Desktop/NotificationBot/bin/head_tests")
set_tests_properties(cpr_head_tests PROPERTIES  _BACKTRACE_TRIPLES "/Users/orlandoortega/Desktop/NotificationBot/libraries/cpr/test/CMakeLists.txt;16;add_test;/Users/orlandoortega/Desktop/NotificationBot/libraries/cpr/test/CMakeLists.txt;42;add_cpr_test;/Users/orlandoortega/Desktop/NotificationBot/libraries/cpr/test/CMakeLists.txt;0;")
add_test(cpr_delete_tests "/Users/orlandoortega/Desktop/NotificationBot/bin/delete_tests")
set_tests_properties(cpr_delete_tests PROPERTIES  _BACKTRACE_TRIPLES "/Users/orlandoortega/Desktop/NotificationBot/libraries/cpr/test/CMakeLists.txt;16;add_test;/Users/orlandoortega/Desktop/NotificationBot/libraries/cpr/test/CMakeLists.txt;43;add_cpr_test;/Users/orlandoortega/Desktop/NotificationBot/libraries/cpr/test/CMakeLists.txt;0;")
add_test(cpr_put_tests "/Users/orlandoortega/Desktop/NotificationBot/bin/put_tests")
set_tests_properties(cpr_put_tests PROPERTIES  _BACKTRACE_TRIPLES "/Users/orlandoortega/Desktop/NotificationBot/libraries/cpr/test/CMakeLists.txt;16;add_test;/Users/orlandoortega/Desktop/NotificationBot/libraries/cpr/test/CMakeLists.txt;44;add_cpr_test;/Users/orlandoortega/Desktop/NotificationBot/libraries/cpr/test/CMakeLists.txt;0;")
add_test(cpr_callback_tests "/Users/orlandoortega/Desktop/NotificationBot/bin/callback_tests")
set_tests_properties(cpr_callback_tests PROPERTIES  _BACKTRACE_TRIPLES "/Users/orlandoortega/Desktop/NotificationBot/libraries/cpr/test/CMakeLists.txt;16;add_test;/Users/orlandoortega/Desktop/NotificationBot/libraries/cpr/test/CMakeLists.txt;45;add_cpr_test;/Users/orlandoortega/Desktop/NotificationBot/libraries/cpr/test/CMakeLists.txt;0;")
add_test(cpr_raw_body_tests "/Users/orlandoortega/Desktop/NotificationBot/bin/raw_body_tests")
set_tests_properties(cpr_raw_body_tests PROPERTIES  _BACKTRACE_TRIPLES "/Users/orlandoortega/Desktop/NotificationBot/libraries/cpr/test/CMakeLists.txt;16;add_test;/Users/orlandoortega/Desktop/NotificationBot/libraries/cpr/test/CMakeLists.txt;46;add_cpr_test;/Users/orlandoortega/Desktop/NotificationBot/libraries/cpr/test/CMakeLists.txt;0;")
add_test(cpr_options_tests "/Users/orlandoortega/Desktop/NotificationBot/bin/options_tests")
set_tests_properties(cpr_options_tests PROPERTIES  _BACKTRACE_TRIPLES "/Users/orlandoortega/Desktop/NotificationBot/libraries/cpr/test/CMakeLists.txt;16;add_test;/Users/orlandoortega/Desktop/NotificationBot/libraries/cpr/test/CMakeLists.txt;47;add_cpr_test;/Users/orlandoortega/Desktop/NotificationBot/libraries/cpr/test/CMakeLists.txt;0;")
add_test(cpr_patch_tests "/Users/orlandoortega/Desktop/NotificationBot/bin/patch_tests")
set_tests_properties(cpr_patch_tests PROPERTIES  _BACKTRACE_TRIPLES "/Users/orlandoortega/Desktop/NotificationBot/libraries/cpr/test/CMakeLists.txt;16;add_test;/Users/orlandoortega/Desktop/NotificationBot/libraries/cpr/test/CMakeLists.txt;48;add_cpr_test;/Users/orlandoortega/Desktop/NotificationBot/libraries/cpr/test/CMakeLists.txt;0;")
add_test(cpr_error_tests "/Users/orlandoortega/Desktop/NotificationBot/bin/error_tests")
set_tests_properties(cpr_error_tests PROPERTIES  _BACKTRACE_TRIPLES "/Users/orlandoortega/Desktop/NotificationBot/libraries/cpr/test/CMakeLists.txt;16;add_test;/Users/orlandoortega/Desktop/NotificationBot/libraries/cpr/test/CMakeLists.txt;49;add_cpr_test;/Users/orlandoortega/Desktop/NotificationBot/libraries/cpr/test/CMakeLists.txt;0;")
add_test(cpr_alternating_tests "/Users/orlandoortega/Desktop/NotificationBot/bin/alternating_tests")
set_tests_properties(cpr_alternating_tests PROPERTIES  _BACKTRACE_TRIPLES "/Users/orlandoortega/Desktop/NotificationBot/libraries/cpr/test/CMakeLists.txt;16;add_test;/Users/orlandoortega/Desktop/NotificationBot/libraries/cpr/test/CMakeLists.txt;50;add_cpr_test;/Users/orlandoortega/Desktop/NotificationBot/libraries/cpr/test/CMakeLists.txt;0;")
add_test(cpr_util_tests "/Users/orlandoortega/Desktop/NotificationBot/bin/util_tests")
set_tests_properties(cpr_util_tests PROPERTIES  _BACKTRACE_TRIPLES "/Users/orlandoortega/Desktop/NotificationBot/libraries/cpr/test/CMakeLists.txt;16;add_test;/Users/orlandoortega/Desktop/NotificationBot/libraries/cpr/test/CMakeLists.txt;51;add_cpr_test;/Users/orlandoortega/Desktop/NotificationBot/libraries/cpr/test/CMakeLists.txt;0;")
